services:
    database:
        restart: unless-stopped
        ports: !reset []

    app:
        restart: unless-stopped
        ports: !override
            - "127.0.0.1:8080:80"
        env_file:
            - path: .env.local
              required: true
